Repository 4-frame-photos-map/frontend, pull requests merged in 2023-04, with the labels that each got.

#33 feat: #26/ 지점 상세 페이지 구현 및 타입 수정
  public/svg/blank_star.svg
  public/svg/blank_star_black.svg
  public/svg/checkbox_disable.svg
  public/svg/checked_star.svg
  public/svg/checked_star_black.svg
  public/svg/half_star.svg
  public/svg/half_star_black.svg
  public/svg/map.svg
  public/svg/marker.svg
  public/svg/share.svg
  src/apis/auth/auth.d.ts
  src/apis/auth/authApi.ts
  src/apis/favorite/favorite.d.ts
  src/apis/favorite/favoriteApi.ts
  src/apis/member/member.d.ts
  src/apis/member/memberApi.ts
  src/apis/review/review.d.ts
  src/apis/review/reviewApi.ts
  src/apis/shop/shop.d.ts
  src/apis/shop/shopApi.ts
  src/apis/title/title.d.ts
  src/apis/title/titleApi.ts
  src/components/common/ReviewItem.tsx
  src/components/common/ShopLayout.tsx
  src/components/common/StarRate.tsx
  src/hooks/useGetShop.ts
  src/pages/_app.tsx
  src/pages/auth/kakao.tsx
  src/pages/shopDetail/[id].tsx
  src/pages/shopDetail/index.tsx
  src/styles/globals.css
  src/utils/dateFormat.ts
Labels: feat

#35 feat: #28/ 리뷰작성 페이지 구현
  public/svg/checkbox_active.svg
  public/svg/checkbox_blank.svg
  src/components/common/Button.tsx
  src/components/common/Checkbox.tsx
  src/components/common/Textarea.tsx
  src/hooks/usePostReview.ts
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
  src/utils/dateFormat.ts
Labels: feat, refactor

#45 refactor: #39/ 지점 상세 & 리뷰 작성 페이지 수정사항 반영
  public/svg/plus.svg
  src/apis/auth/auth.d.ts
  src/apis/auth/authApi.ts
  src/apis/favorite/favorite.d.ts
  src/apis/favorite/favoriteApi.ts
  src/apis/member/memberApi.ts
  src/apis/review/review.d.ts
  src/apis/shop/shop.d.ts
  src/apis/shop/shopApi.ts
  src/apis/title/titleApi.ts
  src/components/common/Checkbox.tsx
  src/components/common/ReviewItem.tsx
  src/hooks/useGetReview.ts
  src/pages/auth/kakao.tsx
  src/pages/my/reviews/edit.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
  src/utils/dateFormat.ts
Labels: feat, refactor

#46 refactor: #39/ 리뷰 수정 페이지 디자인 수정사항 반영
  src/components/common/Checkbox.tsx
  src/components/common/Textarea.tsx
  src/pages/my/reviews/edit.tsx
Labels: refactor

#47 feat: #42/찜 페이지 API 연동 및 관련 기능 구현
  src/apis/shop/shop.d.ts
  src/apis/shop/shopApi.ts
  src/components/common/BrandTag.tsx
  src/components/common/Menu.tsx
  src/components/common/NavBar.tsx
  src/components/common/ToastMessage.tsx
  src/components/home/ShopModal.tsx
  src/components/wish/FavoriteButton.tsx
  src/components/wish/WishItem.tsx
  src/hooks/useDeleteFavorite.ts
  src/hooks/useGetFavorite.ts
  src/hooks/usePostFavorite.ts
  src/pages/_app.tsx
  src/pages/home/index.tsx
  src/pages/shopDetail/index.tsx
  src/pages/wish/index.tsx
Labels: feat

#48 refactor: #38/ 파일 구조 수정 & nextjs script사용
  src/apis/instance.ts
  src/apis/member/member.d.ts
  src/apis/member/memberApi.ts
  src/apis/shop/shop.d.ts
  src/components/common/Scripts.tsx
  src/components/home/ShopModal.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Layout.tsx
  src/components/layout/PageLayout.tsx
  src/components/layout/ShopLayout.tsx
  src/components/wish/FavoriteButton.tsx
  src/hooks/mutations/useDeleteFavorite.ts
  src/hooks/mutations/useDeleteReview.ts
  src/hooks/mutations/usePatchReview.ts
  src/hooks/mutations/usePostFavorite.ts
  src/hooks/mutations/usePostReview.ts
  src/hooks/queries/useGetFavorite.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useGetReview.ts
  src/hooks/queries/useGetShop.ts
  src/hooks/useMapScriptLoad.ts
  src/pages/_app.tsx
  src/pages/auth/kakao.tsx
  src/pages/auth/login.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/inquiry.tsx
  src/pages/location/index.tsx
  src/pages/my/edit.tsx
  src/pages/my/index.tsx
  src/pages/my/reviews/edit.tsx
  src/pages/my/reviews/index.tsx
  src/pages/my/setting.tsx
  src/pages/my/titles.tsx
  src/pages/notice.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
  src/pages/terms.tsx
  src/pages/wish/index.tsx
Labels: refactor

#49 feat: #40/ 닉네임 수정 구현
  src/apis/member/memberApi.ts
  src/hooks/mutations/usePatchProfile.ts
  src/hooks/useDebounce.ts
  src/pages/my/edit.tsx
Labels: feat

#50 fix: #37/카테고리 버그 수정
  src/components/home/Category.tsx
  src/styles/globals.css
Labels: fix

#57 feat: #53/ 홈 화면 기능 구현
  public/svg/marker_black.svg
  public/svg/marker_blue.svg
  public/svg/marker_gray.svg
  public/svg/marker_pink.svg
  public/svg/marker_select_black.svg
  public/svg/marker_select_blue.svg
  public/svg/marker_select_gray.svg
  public/svg/marker_select_pink.svg
  public/svg/marker_select_white.svg
  public/svg/marker_white.svg
  src/components/common/Map.tsx
  src/components/home/ResearchButton.tsx
  src/components/home/ShopModal.tsx
  src/components/home/TrackerButton.tsx
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
Labels: feat, refactor

#59 feat: #51/검색 기능 구현
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/prettier/index.js
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  public/svg/navbar/gray-star.svg
  public/svg/navbar/list.svg
  public/svg/navbar/location.svg
  public/svg/navbar/map.svg
  public/svg/navbar/search-icon.svg
  public/svg/wish/filled-bookmark.svg
  public/svg/wish/lined-bookmark.svg
  src/apis/shop/shop.d.ts
  src/components/common/BrandTag.tsx
  src/components/common/Modal.tsx
  src/components/common/NavBar.tsx
  src/components/home/Category.tsx
  src/components/navbar/Search.tsx
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/WishItem.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/auth/login.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
  src/pages/wish/index.tsx
  tailwind.config.js
Labels: feat

#60 refactor: #54/ 모달 bg 수정
  src/components/common/Modal.tsx
Labels: refactor

#61 feat: /#56/로그아웃&회원탈퇴 구현
  src/components/common/BrandTag.tsx
  src/pages/my/setting.tsx
Labels: feat, refactor

#62 feat: #55/ 비로그인 유저 로직 구현
  src/apis/instance.ts
  src/components/common/Map.tsx
  src/pages/_app.tsx
  src/pages/my/index.tsx
  src/utils/getImgSrc.ts
Labels: feat, refactor

#63 feat : build.sh
  build.sh
Labels: feat

#64 feat : build.sh
  build.sh
Labels: refactor

#66 feat: #65/node env 구분
  config.ts
  src/apis/instance.ts
  src/components/common/Modal.tsx
  src/pages/auth/login.tsx
Labels: feat

#70 refactor: #69/checkbox 토글 방식 구현
  src/components/common/Checkbox.tsx
Labels: refactor

#74 fix: #71/비로그인 시 상세페이지 접근 불가능한 현상 해결
  src/apis/favorite/favoriteApi.ts
  src/components/common/NavBar.tsx
  src/components/common/ToastMessage.tsx
  src/components/home/ShopModal.tsx
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/FavoriteButton.tsx
  src/components/wish/WishItem.tsx
  src/hooks/mutations/useDeleteFavorite.ts
  src/hooks/mutations/usePostFavorite.ts
  src/hooks/queries/useGetFavorite.ts
  src/hooks/queries/useGetShop.ts
  src/pages/_app.tsx
  src/pages/shopDetail/index.tsx
  src/pages/wish/index.tsx
Labels: fix

#79 refactor : 닉네임 수정시 validation 메시지 추가
  src/pages/my/edit.tsx
Labels: refactor

#81 feat: #80/ 키워드 검색결과 지도에 마커 표시 구현
  src/@types/index.d.ts
  src/components/common/Map.tsx
  src/components/common/NavBar.tsx
  src/components/navbar/Search.tsx
  src/pages/home/index.tsx
Labels: feat

#83 fix: #72/ 모바일에서 지도 주변 컴포넌트 고정되지 않는 현상 해결
  src/components/common/Map.tsx
  src/components/home/Category.tsx
  src/components/home/ShopModal.tsx
  src/pages/home/index.tsx
Labels: fix

#85 feat: #84/ 찜 삭제 낙관적 업데이트 구현 & shopModal 찜 버그 수정
  src/components/common/Scripts.tsx
  src/components/home/ShopModal.tsx
  src/components/wish/FavoriteButton.tsx
  src/components/wish/WishItem.tsx
  src/hooks/mutations/useDeleteFavorite.ts
  src/hooks/mutations/usePostFavorite.ts
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/utils/getImgSrc.ts
Labels: feat, refactor, fix

#87 fix: #86/ 지점 상세페이지 새로고침 시 지도 불러오지 못하는 현상 수정
  src/components/home/ShopModal.tsx
  src/components/navbar/SearchResult.tsx
  src/pages/home/index.tsx
  src/pages/shopDetail/index.tsx
Labels: refactor, fix

#95 refactor: #88/Redirect 설정
  next.config.js
  src/components/common/Menu.tsx
Labels: refactor

#96 refactor: #93/ refresh-token 에러핸들링 수정
  src/apis/instance.ts
Labels: refactor

#97 refactor: #89/찜 페이지 NavBar 요소 상태 변경
  src/components/common/NavBar.tsx
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/my/edit.tsx
  src/pages/my/index.tsx
  src/pages/my/reviews/index.tsx
  src/pages/my/setting.tsx
  src/pages/my/titles.tsx
  src/pages/wish/index.tsx
Labels: refactor

#99 refactor: #98/ api 타입 수정사항 반영
  src/apis/favorite/favorite.d.ts
  src/apis/favorite/favoriteApi.ts
  src/apis/shop/shop.d.ts
  src/apis/shop/shopApi.ts
  src/components/common/Map.tsx
  src/components/common/NavBar.tsx
  src/hooks/queries/useGetFavorite.ts
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/pages/wish/index.tsx
Labels: refactor

#100 feat: #90/지도지역명 표시
  src/components/common/NavBar.tsx
  src/pages/home/index.tsx
Labels: feat

#102 refactor: #101/SearchList & SearchResult 응답값 수정
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
Labels: refactor

#105 refactor: #104/지도 로딩 중일 때 지도지역명 안 보이게 수정
  src/components/common/NavBar.tsx
Labels: refactor

#106 refactor: #103/ review type 수정 및 리뷰 로직 수정
  src/apis/review/review.d.ts
  src/apis/review/reviewApi.ts
  src/apis/shop/shop.d.ts
  src/components/common/ReviewItem.tsx
  src/hooks/mutations/useDeleteReview.ts
  src/hooks/mutations/usePatchReview.ts
  src/hooks/mutations/usePostReview.ts
  src/pages/my/reviews/edit.tsx
  src/pages/my/reviews/index.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
Labels: refactor

#107 feat: #94/ 카카오톡 공유 구현
  src/components/common/Scripts.tsx
  src/pages/_app.tsx
  src/pages/my/reviews/index.tsx
  src/pages/shopDetail/index.tsx
Labels: feat, refactor

#108 refactor: #91/ 마커 이미지 교체
  public/svg/marker.svg
  public/svg/marker_black.svg
  public/svg/marker_blue.svg
  public/svg/marker_gray.svg
  public/svg/marker_pink.svg
  public/svg/marker_select.svg
  public/svg/marker_select_black.svg
  public/svg/marker_select_gray.svg
  public/svg/marker_select_pink.svg
  public/svg/marker_select_white.svg
  public/svg/marker_white.svg
  src/components/common/Map.tsx
  src/components/common/Scripts.tsx
  src/utils/getImgSrc.ts
Labels: refactor

#110 fix: #109/검색 하이라이팅 버그 수정
  src/components/navbar/Search.tsx
  src/components/navbar/SearchResult.tsx
  src/components/navbar/TextHighlighted.tsx
Labels: fix

#113 feat: #92/ 내주변 페이지 구현
  next.config.js
  src/apis/instance.ts
  src/components/common/LocationMap.tsx
  src/components/home/Category.tsx
  src/components/location/ShopItem.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/pages/location/index.tsx
Labels: feat

#114 refactor : #111/ 마커 이미지 교체
  public/svg/marker.svg
  public/svg/marker_select.svg
Labels: refactor
