Repository 4-frame-photos-map/frontend, pull requests merged in 2023-05, with the labels that each got.

#118 design : #116/ 리뷰 수정,삭제 버튼 수정사항 반영
  src/pages/my/reviews/index.tsx
Labels: design

#117 design : #115/ 찜목록 페이지 짤림 현상 수정
  src/pages/wish/index.tsx
Labels: design

#120 fix: #119/찜 삭제 후 토스트 메세지 안 보이는 현상 수정
  src/components/wish/WishItem.tsx
  src/pages/location/index.tsx
Labels: fix

#128 refactor: #121/ shop api 변경사항 수정
  src/apis/shop/shopApi.ts
  src/components/common/LocationMap.tsx
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
Labels: refactor

#129 feat: #127/로그인 스플래시 화면 및 성공 페이지 구현
  public/svg/login/4-cut-photos-map.svg
  public/svg/login/login-logo.svg
  public/svg/login/pin-badge-orange.svg
  public/svg/login/pin-badge-skyblue.svg
  public/svg/login/splash-image.svg
  public/svg/login/success-image.svg
  src/components/common/SplashLogin.tsx
  src/components/wish/WishItem.tsx
  src/pages/auth/kakao.tsx
  src/pages/auth/login.tsx
Labels: feat

#130 add: #126/Recoil 설정 및 curPos atom 생성
  .yarn/cache/hamt_plus-npm-1.0.2-67a52ee1df-af26ea32db.zip
  .yarn/cache/recoil-npm-0.7.7-4452f58b67-65edecbcb8.zip
  package.json
  src/components/common/LocationMap.tsx
  src/components/common/Map.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/_app.tsx
  src/pages/auth/kakao.tsx
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
  src/pages/wish/index.tsx
  src/recoil/position.ts
  tsconfig.json
  yarn.lock
Labels: add

#131 refactor: #125/내 주변 결과창만 스크롤 되도록 수정
  src/components/common/LocationMap.tsx
  src/pages/location/index.tsx
Labels: refactor

#133 refactor: #132/shopDetail router push 쿼리 파라미터 수정
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/WishItem.tsx
  src/pages/shopDetail/index.tsx
Labels: refactor

#137 refactor: #136/ 유저 로그인 상태, 모달 상태 전역 관리
  src/components/home/ShopModal.tsx
  src/components/layout/Layout.tsx
  src/components/location/ShopItem.tsx
  src/components/wish/FavoriteButton.tsx
  src/pages/_app.tsx
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
  src/recoil/modalAtom.ts
  src/recoil/userAtom.ts
  src/utils/token.ts
Labels: refactor

#138 fix: #134/현재 위치 중심 거리 문제 및 Url 마스킹 처리
  src/@types/index.d.ts
  src/apis/shop/shopApi.ts
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/WishItem.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
  src/recoil/positionAtom.ts
Labels: fix

#140 fix: #139/배포 후 에러 발생으로 undefined 타입 제거
  src/@types/index.d.ts
  src/recoil/positionAtom.ts
Labels: fix

#142 fix: #141/검색어 value 없을 때 초기 상태로 설정
  src/components/navbar/Search.tsx
  src/components/navbar/TextHighlighted.tsx
  src/pages/_app.tsx
Labels: fix

#146 refactor: #144/ review 관련 사항 수정
  src/hooks/mutations/useDeleteReview.ts
  src/hooks/mutations/usePostReview.ts
  src/pages/my/reviews/edit.tsx
  src/pages/my/reviews/index.tsx
  src/pages/wish/index.tsx
Labels: refactor

#148 feat: #147/favicon, Head title 추가
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/auth/login.tsx
  src/pages/my/reviews/edit.tsx
Labels: feat

#159 refactor: #152/로그인 성공 후 히스토리 스택 안 쌓이게 수정
  src/pages/auth/kakao.tsx
Labels: refactor

#161 fix : #160/ 배포서버와 개발서버 redirect-uri 구분
  src/pages/auth/login.tsx
Labels: fix

#162 refactor: #155/ 지점 상세 페이지 리팩토링 & 리뷰로 명칭 통일
  src/components/common/Button.tsx
  src/hooks/queries/useGetReview.ts
  src/pages/my/index.tsx
  src/pages/my/reviews/edit.tsx
  src/pages/my/reviews/index.tsx
  src/pages/my/setting.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
Labels: refactor

#163 refactor: #157/ 위치 이슈 수정
  src/components/common/LocationMap.tsx
  src/components/common/Map.tsx
  src/pages/shopDetail/index.tsx
Labels: refactor

#165 fix : #156/ 리뷰 공백 처리 수정
  src/pages/my/reviews/edit.tsx
  src/pages/shopDetail/review.tsx
Labels: fix

#166 feat: #150/지점 칭호 기능 구현
  public/svg/navbar/danger.svg
  public/svg/shop-title-clean.svg
  public/svg/shop-title-hot-place.svg
  src/apis/instance.ts
  src/apis/shop/shop.d.ts
  src/components/common/BrandTag.tsx
  src/components/common/ShopTitle.tsx
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/components/navbar/Search.tsx
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/WishItem.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
Labels: feat

#169 fix: #168/사파리 및 모바일 브라우저에서 svg 깨짐 현상 수정
  public/svg/shop-title-clean.svg
  public/svg/shop-title-hot-place.svg
Labels: fix

#172 design: #171/검색 및 찜 총개수 디자인 추가
  src/components/common/NavBar.tsx
  src/components/common/ShopTitle.tsx
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/pages/shopDetail/index.tsx
  src/pages/wish/index.tsx
Labels: design

#175 fix: #170/#173/ 검색 후 기존 모달 유지 & 검색 결과 필터링
  src/components/common/NavBar.tsx
  src/pages/home/index.tsx
  src/pages/location/index.tsx
Labels: fix

#177 refactor: #176/ 내주변 페이지 이동시 지점 표시되지않는 문제 수정
  src/components/common/LocationMap.tsx
  src/components/common/Map.tsx
  src/components/common/NavBar.tsx
  src/hooks/mutations/useDeleteFavorite.ts
  src/hooks/mutations/usePostFavorite.ts
  src/pages/home/index.tsx
  src/pages/location/index.tsx
Labels: refactor

#178 feat: #149/회원 칭호 기능 구현
  .vscode/settings.json
  public/svg/check.svg
  public/svg/close.svg
  public/svg/disabled_check.svg
  public/svg/navbar/danger.svg
  public/svg/navbar/info.svg
  public/svg/union.svg
  src/apis/title/title.d.ts
  src/apis/title/titleApi.ts
  src/components/common/NavBar.tsx
  src/components/title/TitleInfo.tsx
  src/components/title/TitleModal.tsx
  src/components/wish/WishItem.tsx
  src/hooks/mutations/usePatchTitle.ts
  src/hooks/queries/useGetMemberTitle.ts
  src/pages/my/index.tsx
  src/pages/my/titles.tsx
Labels: feat

#180 feat: #158/ 내 주변 페이지 반경 조절 기능 추가
  src/components/home/Category.tsx
  src/components/location/RadiusModal.tsx
  src/hooks/queries/useGetShop.ts
  src/pages/location/index.tsx
  src/styles/globals.css
Labels: feat, refactor

#181 feat: #179/대표칭호 컴포넌트 작성 및 적용
  src/apis/review/review.d.ts
  src/apis/shop/shop.d.ts
  src/apis/title/title.d.ts
  src/apis/title/titleApi.ts
  src/components/common/ReviewItem.tsx
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/components/title/ShopTitle.tsx
  src/components/title/TitleBadge.tsx
  src/components/title/TitleInfo.tsx
  src/components/title/TitleModal.tsx
  src/hooks/mutations/usePatchTitle.ts
  src/pages/my/index.tsx
  src/pages/my/titles.tsx
  src/pages/shopDetail/index.tsx
Labels: feat

#184 fix: #183/ 내주변 페이지 특정 브랜드 필터링 상태에서 반경 조절시 전체 지점 받아오지 못하는 현상 수정
  src/apis/shop/shop.d.ts
  src/apis/shop/shopApi.ts
  src/hooks/queries/useGetShop.ts
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/shopDetail/index.tsx
Labels: refactor, fix

#186 refactor: #185/획득과 미획득한 칭호에 대한 문구 수정 및 칭호 모달 수정
  src/components/title/TitleModal.tsx
  src/pages/my/titles.tsx
Labels: refactor

#188 feat: #187/faq 페이지 구현
  src/@types/index.d.ts
  src/components/faq/FaqModal.tsx
  src/pages/faq.tsx
  src/pages/inquiry.tsx
  src/pages/my/index.tsx
  src/utils/faqLists.ts
Labels: feat

#192 refactor: #191/ 내주변 페이지 지도 정방향 수정 및 next link 사용
  src/components/common/Map.tsx
  src/components/common/Modal.tsx
  src/components/common/NavBar.tsx
  src/components/home/ShopModal.tsx
  src/components/location/ShopItem.tsx
  src/components/my/SettingItem.tsx
  src/components/my/SettingList.tsx
  src/components/navbar/SearchList.tsx
  src/components/navbar/SearchResult.tsx
  src/components/wish/WishItem.tsx
  src/pages/faq.tsx
  src/pages/location/index.tsx
  src/pages/my/index.tsx
  src/pages/my/setting.tsx
Labels: refactor

#194 refactor: #193/ seo 컴포넌트 구현
  src/components/common/Seo.tsx
  src/components/common/SplashLogin.tsx
  src/components/my/SettingItem.tsx
  src/components/my/SettingList.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/auth/login.tsx
  src/pages/faq.tsx
  src/pages/home/index.tsx
  src/pages/location/index.tsx
  src/pages/my/edit.tsx
  src/pages/my/index.tsx
  src/pages/my/reviews/edit.tsx
  src/pages/my/reviews/index.tsx
  src/pages/my/setting.tsx
  src/pages/my/titles.tsx
  src/pages/notice.tsx
  src/pages/shopDetail/index.tsx
  src/pages/shopDetail/review.tsx
  src/pages/terms.tsx
  src/pages/wish/index.tsx
Labels: refactor
